"""baseline

Revision ID: 08a70879788f
Revises: 
Create Date: 2026-05-09 22:30:32.863228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08a70879788f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector required for embedding columns. Idempotent — bootstrap.py also
    # ensures this before alembic runs, so managed-Postgres deploys where the
    # app role lacks CREATE EXTENSION can pre-create out-of-band and IF NOT
    # EXISTS makes both call sites a no-op.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comfyui_workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('json_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("slug LIKE '%/%' AND slug NOT LIKE '/%' AND slug NOT LIKE '%/'", name='ck_comfyui_workflow_slug_namespaced'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'version', name='uix_comfyui_workflow_slug_version')
    )
    op.create_index(op.f('ix_comfyui_workflows_slug'), 'comfyui_workflows', ['slug'], unique=False)
    op.create_index('ix_comfyui_workflows_slug_active', 'comfyui_workflows', ['slug', 'is_active'], unique=False)
    op.create_index('ix_comfyui_workflows_slug_pattern', 'comfyui_workflows', [sa.literal_column('slug text_pattern_ops')], unique=False)
    op.create_table('marketplace_catalogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_type', sa.Enum('PROVIDERS', 'BLUEPRINTS', 'WORKFLOWS', 'COMFYUI', 'PROMPTS', name='catalogtype', create_constraint=True), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_tag', sa.String(length=100), nullable=True),
    sa.Column('catalog_data', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fetch_error', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_marketplace_catalogs_fetched', 'marketplace_catalogs', ['fetched_at'], unique=False)
    op.create_index('ix_marketplace_catalogs_type_active', 'marketplace_catalogs', ['catalog_type', 'is_active'], unique=False)
    op.create_table('oauth_states',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index('ix_oauth_states_expires_at', 'oauth_states', ['expires_at'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending_approval', 'active', 'suspended', name='organization_status', create_constraint=True), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('activated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('activated_by', sa.UUID(), nullable=True),
    sa.Column('activation_method', sa.Enum('MANUAL', 'SUBSCRIPTION', 'AUTO', name='activationmethod', create_constraint=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activated_by'], ['users.id'], name='fk_organizations_activated_by_users', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('ix_organizations_status'), 'organizations', ['status'], unique=False)
    op.create_table('package_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_type', sa.Enum('PROVIDER', 'WORKFLOW', 'BLUEPRINT', 'COMFYUI', 'PROMPT', name='packagetype', create_constraint=True), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('json_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('LOCAL', 'MARKETPLACE', 'SUPER_ADMIN', name='packagesource', create_constraint=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("slug LIKE '%/%' AND slug NOT LIKE '/%' AND slug NOT LIKE '%/'", name='ck_package_versions_slug_namespaced'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'package_type', 'version', name='uix_package_versions_slug_type_version')
    )
    op.create_index('ix_package_versions_active', 'package_versions', ['slug', 'package_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_package_versions_slug'), 'package_versions', ['slug'], unique=False)
    op.create_index('ix_package_versions_slug_pattern', 'package_versions', [sa.literal_column('slug text_pattern_ops')], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider_type', sa.Enum('API', 'INFRASTRUCTURE', 'HYBRID', 'INTERNAL', 'CUSTOM', name='providertype', create_constraint=True), nullable=False),
    sa.Column('endpoint_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='providerstatus', create_constraint=True), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('client_metadata', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("slug LIKE '%/%' AND slug NOT LIKE '/%' AND slug NOT LIKE '%/'", name='ck_provider_slug_namespaced'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'version', name='uix_provider_slug_version')
    )
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=False)
    op.create_index(op.f('ix_providers_slug'), 'providers', ['slug'], unique=False)
    op.create_index('ix_providers_slug_pattern', 'providers', [sa.literal_column('slug text_pattern_ops')], unique=False)
    op.create_table('site_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.String(length=100), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_content_page_id'), 'site_content', ['page_id'], unique=True)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('organization_secrets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('secret_type', sa.String(length=50), nullable=False),
    sa.Column('secret_data', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uix_org_secret_name')
    )
    op.create_index('ix_org_secrets_org_active', 'organization_secrets', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_organization_secrets_organization_id'), 'organization_secrets', ['organization_id'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('chunks', sa.JSON(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('CUSTOM', 'SUPER_ADMIN', 'MARKETPLACE', 'UNINSTALLED', name='promptsource', create_constraint=True), nullable=False),
    sa.Column('marketplace_slug', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('scope', sa.Enum('PERSONAL', 'ORGANIZATION', name='promptscope', create_constraint=True), nullable=False),
    sa.Column('publish_status', sa.Enum('PENDING', 'REJECTED', name='promptpublishstatus', create_constraint=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("marketplace_slug IS NULL OR (marketplace_slug LIKE '%/%' AND marketplace_slug NOT LIKE '/%' AND marketplace_slug NOT LIKE '%/')", name='ck_prompt_marketplace_slug_namespaced'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompts_created_by', 'prompts', ['created_by'], unique=False)
    op.create_index('ix_prompts_marketplace_slug_pattern', 'prompts', [sa.literal_column('marketplace_slug text_pattern_ops')], unique=False, postgresql_where=sa.text('marketplace_slug IS NOT NULL'))
    op.create_index('ix_prompts_org_category', 'prompts', ['organization_id', 'category'], unique=False)
    op.create_index('ix_prompts_org_enabled', 'prompts', ['organization_id', 'is_enabled'], unique=False)
    op.create_index('ix_prompts_org_scope', 'prompts', ['organization_id', 'scope'], unique=False)
    op.create_index(op.f('ix_prompts_organization_id'), 'prompts', ['organization_id'], unique=False)
    op.create_index('uix_prompt_org_marketplace_slug', 'prompts', ['organization_id', 'marketplace_slug'], unique=True, postgresql_where=sa.text('marketplace_slug IS NOT NULL'))
    op.create_table('provider_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credential_type', sa.String(length=50), nullable=False),
    sa.Column('secret_data', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_token_type', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_credentials_provider_org', 'provider_credentials', ['provider_id', 'organization_id'], unique=False)
    op.create_table('provider_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('service_type', sa.Enum('core', 'flow', 'ai', 'productivity', 'communication', 'storage', 'social_media', 'human_in_the_loop', 'transform', 'network', name='servicetype', create_constraint=True), server_default='core', nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=True),
    sa.Column('parameter_schema', sa.JSON(), nullable=False),
    sa.Column('result_schema', sa.JSON(), nullable=False),
    sa.Column('example_parameters', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('client_metadata', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'service_id', name='uix_provider_service_id')
    )
    op.create_index(op.f('ix_provider_services_service_id'), 'provider_services', ['service_id'], unique=False)
    op.create_index('ix_provider_services_service_type_active', 'provider_services', ['service_type', 'is_active'], unique=False)
    op.create_table('queues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('queue_type', sa.Enum('DEFAULT', 'PRIORITY', name='queuetype', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'DRAINING', 'STOPPED', name='queuestatus', create_constraint=True), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('max_pending_jobs', sa.Integer(), nullable=False),
    sa.Column('default_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('resource_requirements', sa.JSON(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('client_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organization_id', name='uix_queue_name_org')
    )
    op.create_index('ix_queues_organization_status', 'queues', ['organization_id', 'status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_login', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('role_changed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('logged_out_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.Enum('USER', 'ADMIN', 'SUPER_ADMIN', 'SYSTEM', 'ANONYMOUS', 'UNKNOWN', name='auditactortype', create_constraint=True), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'REVEAL', 'LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'ACTIVATE', 'DEACTIVATE', 'SUSPEND', 'VIEW', 'ACCESS_DENIED', 'DOWNLOAD', 'TOKEN_REFRESH', 'INSTALL', 'UNINSTALL', 'INVITE', 'ROLE_CHANGE', 'TRIGGER', 'APPROVE', 'REJECT', 'BYPASS', 'TIMEOUT', 'CANCEL', 'RETRY', 'RERUN', 'REGENERATE', 'UPLOAD', name='auditaction', create_constraint=True), nullable=False),
    sa.Column('resource_type', sa.Enum('SECRET', 'CREDENTIAL', 'USER', 'ORGANIZATION', 'WORKFLOW', 'BLUEPRINT', 'INSTANCE', 'INSTANCE_STEP', 'PROVIDER', 'SERVICE', 'PACKAGE', 'FILE', 'AUDIT_LOG', name='resourcetype', create_constraint=True), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='auditseverity', create_constraint=True), nullable=False),
    sa.Column('category', sa.Enum('SECURITY', 'CONFIGURATION', 'ACCESS', 'AUDIT', name='auditcategory', create_constraint=True), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='auditstatus', create_constraint=True), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_events_actor_created', 'audit_events', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index('ix_audit_events_category_created', 'audit_events', ['category', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_org_created', 'audit_events', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_index('ix_audit_events_resource', 'audit_events', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_type'), 'audit_events', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_events_severity'), 'audit_events', ['severity'], unique=False)
    op.create_index('ix_audit_events_severity_created', 'audit_events', ['severity', 'created_at'], unique=False)
    op.create_table('blueprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'DEPRECATED', 'ARCHIVED', name='blueprintstatus', create_constraint=True), nullable=False),
    sa.Column('category', sa.Enum('GENERAL', 'DATA_PROCESSING', 'INTEGRATION', 'AUTOMATION', 'ANALYTICS', 'CUSTOM', name='blueprintcategory', create_constraint=True), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('client_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organization_id', 'version', name='uix_blueprint_name_org_version')
    )
    op.create_index('ix_blueprints_organization_status', 'blueprints', ['organization_id', 'status'], unique=False)
    op.create_table('notification_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('channel_config', sa.JSON(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_type', name='uix_user_channel_type')
    )
    op.create_index('ix_notification_channels_user', 'notification_channels', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', name='notificationstatus', create_constraint=True), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='notificationpriority', create_constraint=True), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('action_url', sa.String(length=512), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('client_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_channel_type', 'notifications', ['channel_type'], unique=False)
    op.create_index('ix_notifications_organization_status', 'notifications', ['organization_id', 'status'], unique=False)
    op.create_index('ix_notifications_recipient_status', 'notifications', ['recipient_id', 'status'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('blueprint_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED', 'DEBUG', name='workflowstatus', create_constraint=True), nullable=False),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'SCHEDULE', 'WEBHOOK', 'EVENT', 'API', name='workflowtriggertype', create_constraint=True), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'CRITICAL', name='workflowpriority', create_constraint=True), nullable=False),
    sa.Column('execution_mode', sa.Enum('IMMEDIATE', 'QUEUED', name='executionmode', create_constraint=True), nullable=False),
    sa.Column('has_unresolved_refs', sa.Boolean(), nullable=False),
    sa.Column('max_concurrent_instances', sa.Integer(), nullable=False),
    sa.Column('instance_count', sa.Integer(), nullable=False),
    sa.Column('last_instance_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('webhook_token', sa.String(length=64), nullable=True),
    sa.Column('webhook_secret', sa.String(length=256), nullable=True),
    sa.Column('webhook_method', sa.String(length=10), nullable=False),
    sa.Column('webhook_auth_type', sa.String(length=20), nullable=False),
    sa.Column('webhook_auth_header_name', sa.String(length=100), nullable=True),
    sa.Column('webhook_auth_header_value', sa.String(length=500), nullable=True),
    sa.Column('webhook_jwt_secret', sa.String(length=256), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('client_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Enum('PERSONAL', 'ORGANIZATION', name='workflowscope', create_constraint=True), nullable=False),
    sa.Column('publish_status', sa.Enum('PENDING', 'REJECTED', name='publishstatus', create_constraint=True), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("slug LIKE '%/%' AND slug NOT LIKE '/%' AND slug NOT LIKE '%/'", name='ck_workflow_slug_namespaced'),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uix_workflow_org_slug')
    )
    op.create_index('ix_workflows_blueprint', 'workflows', ['blueprint_id'], unique=False)
    op.create_index('ix_workflows_created_by_scope', 'workflows', ['created_by', 'scope'], unique=False)
    op.create_index('ix_workflows_has_unresolved_refs', 'workflows', ['organization_id'], unique=False, postgresql_where=sa.text('has_unresolved_refs = TRUE'))
    op.create_index('ix_workflows_organization_scope', 'workflows', ['organization_id', 'scope'], unique=False)
    op.create_index('ix_workflows_organization_status', 'workflows', ['organization_id', 'status'], unique=False)
    op.create_index('ix_workflows_slug_pattern', 'workflows', [sa.literal_column('slug text_pattern_ops')], unique=False)
    op.create_index(op.f('ix_workflows_webhook_token'), 'workflows', ['webhook_token'], unique=True)
    op.create_table('instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'WAITING_FOR_WEBHOOK', 'WAITING_FOR_APPROVAL', 'WAITING_FOR_MANUAL_TRIGGER', 'DEBUG_PAUSED', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', 'INACTIVE', 'ACTIVE', name='instancestatus', create_constraint=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('client_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workflow_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_step_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('failed_step_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('error_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_debug_mode', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_instances_organization_status', 'instances', ['organization_id', 'status'], unique=False)
    op.create_index('ix_instances_status_created', 'instances', ['status', 'created_at'], unique=False)
    op.create_index('ix_instances_workflow_status', 'instances', ['workflow_id', 'status'], unique=False)
    op.create_table('workflow_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trigger_input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('structural_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'version', name='uix_workflow_version_unique')
    )
    op.create_index('ix_workflow_versions_workflow_created', 'workflow_versions', ['workflow_id', 'created_at'], unique=False)
    op.create_index('ix_workflow_versions_workflow_hash', 'workflow_versions', ['workflow_id', 'structural_hash'], unique=False)
    op.create_table('step_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('step_key', sa.String(length=255), nullable=False),
    sa.Column('step_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', 'STOPPED', 'WAITING_APPROVAL', 'WAITING_FOR_MANUAL_TRIGGER', 'CANCELLED', 'TIMEOUT', 'BLOCKED', 'PAUSED', name='stepexecutionstatus', create_constraint=True), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('execution_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('iteration_requests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active_operation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'step_key', name='uq_step_execution_instance_step_key')
    )
    op.create_index(op.f('ix_step_executions_instance_id'), 'step_executions', ['instance_id'], unique=False)
    op.create_index('ix_step_executions_instance_status', 'step_executions', ['instance_id', 'status'], unique=False)
    op.create_index(op.f('ix_step_executions_status'), 'step_executions', ['status'], unique=False)
    op.create_index(op.f('ix_step_executions_step_key'), 'step_executions', ['step_key'], unique=False)
    op.create_table('iteration_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('iteration_index', sa.Integer(), nullable=False),
    sa.Column('iteration_group_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='iterationexecutionstatus', create_constraint=True), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['step_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_id', 'iteration_group_id', 'iteration_index', name='uq_iteration_execution_key')
    )
    op.create_index(op.f('ix_iteration_executions_instance_id'), 'iteration_executions', ['instance_id'], unique=False)
    op.create_index('ix_iteration_executions_instance_step_index', 'iteration_executions', ['instance_id', 'step_id', 'iteration_index'], unique=False)
    op.create_index(op.f('ix_iteration_executions_iteration_group_id'), 'iteration_executions', ['iteration_group_id'], unique=False)
    op.create_index(op.f('ix_iteration_executions_status'), 'iteration_executions', ['status'], unique=False)
    op.create_index(op.f('ix_iteration_executions_step_id'), 'iteration_executions', ['step_id'], unique=False)
    op.create_table('org_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_execution_id', sa.UUID(), nullable=True),
    sa.Column('instance_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('instance_step_id', sa.UUID(), nullable=True),
    sa.Column('file_extension', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('virtual_path', sa.String(length=1024), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('JOB_GENERATED', 'JOB_DOWNLOAD', 'USER_UPLOAD', name='resourcesource', create_constraint=True), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('provider_resource_id', sa.String(length=255), nullable=True),
    sa.Column('provider_url', sa.String(length=2048), nullable=True),
    sa.Column('download_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'AVAILABLE', 'FAILED', 'ORPHANED', 'DELETED', name='resourcestatus', create_constraint=True), nullable=False),
    sa.Column('resource_metadata', sa.JSON(), nullable=False),
    sa.Column('has_thumbnail', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_step_id'], ['step_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_execution_id'], ['step_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_files_instance_id', 'org_files', ['instance_id'], unique=False)
    op.create_index(op.f('ix_org_files_instance_step_id'), 'org_files', ['instance_step_id'], unique=False)
    op.create_index('ix_org_files_job_id', 'org_files', ['job_execution_id'], unique=False)
    op.create_index('ix_org_files_org_id', 'org_files', ['organization_id'], unique=False)
    op.create_index('ix_org_files_source', 'org_files', ['source'], unique=False)
    op.create_index('ix_org_files_status', 'org_files', ['status'], unique=False)
    op.create_index(op.f('ix_org_files_worker_id'), 'org_files', ['worker_id'], unique=False)
    op.create_table('queued_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('enqueued_by', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('instance_id', sa.UUID(), nullable=True),
    sa.Column('queue_name', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', 'STOPPED', 'WAITING_APPROVAL', 'WAITING_FOR_MANUAL_TRIGGER', 'CANCELLED', 'TIMEOUT', 'BLOCKED', 'PAUSED', name='stepexecutionstatus', create_constraint=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('resource_requirements', sa.JSON(), nullable=True),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('enqueued_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('timeout_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('failed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('client_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['step_executions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queued_jobs_enqueued_at'), 'queued_jobs', ['enqueued_at'], unique=False)
    op.create_index(op.f('ix_queued_jobs_enqueued_by'), 'queued_jobs', ['enqueued_by'], unique=False)
    op.create_index(op.f('ix_queued_jobs_instance_id'), 'queued_jobs', ['instance_id'], unique=False)
    op.create_index(op.f('ix_queued_jobs_job_id'), 'queued_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_queued_jobs_organization_id'), 'queued_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_queued_jobs_priority'), 'queued_jobs', ['priority'], unique=False)
    op.create_index(op.f('ix_queued_jobs_queue_name'), 'queued_jobs', ['queue_name'], unique=False)
    op.create_index(op.f('ix_queued_jobs_status'), 'queued_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_queued_jobs_timeout_at'), 'queued_jobs', ['timeout_at'], unique=False)
    op.create_index(op.f('ix_queued_jobs_worker_id'), 'queued_jobs', ['worker_id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('queue_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('IDLE', 'BUSY', 'OFFLINE', name='workerstatus', create_constraint=True), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('queue_labels', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('last_heartbeat', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('current_job_id', sa.UUID(), nullable=True),
    sa.Column('jobs_completed', sa.Integer(), nullable=False),
    sa.Column('is_deregistered', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('memory_percent', sa.Float(), nullable=True),
    sa.Column('memory_used_mb', sa.Integer(), nullable=True),
    sa.Column('memory_total_mb', sa.Integer(), nullable=True),
    sa.Column('disk_percent', sa.Float(), nullable=True),
    sa.Column('gpu_percent', sa.Float(), nullable=True),
    sa.Column('gpu_memory_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_job_id'], ['queued_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workers_heartbeat', 'workers', ['last_heartbeat'], unique=False)
    op.create_index('ix_workers_queue_status', 'workers', ['queue_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workers_queue_status', table_name='workers')
    op.drop_index('ix_workers_heartbeat', table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_queued_jobs_worker_id'), table_name='queued_jobs')
    op.drop_index(op.f('ix_queued_jobs_timeout_at'), table_name='queued_jobs')
    op.drop_index(op.f('ix_queued_jobs_status'), table_name='queued_jobs')
    op.drop_index(op.f('ix_queued_jobs_queue_name'), table_name='queued_jobs')
    op.drop_index(op.f('ix_queued_jobs_priority'), table_name='queued_jobs')
    op.drop_index(op.f('ix_queued_jobs_organization_id'), table_name='queued_jobs')
    op.drop_index(op.f('ix_queued_jobs_job_id'), table_name='queued_jobs')
    op.drop_index(op.f('ix_queued_jobs_instance_id'), table_name='queued_jobs')
    op.drop_index(op.f('ix_queued_jobs_enqueued_by'), table_name='queued_jobs')
    op.drop_index(op.f('ix_queued_jobs_enqueued_at'), table_name='queued_jobs')
    op.drop_table('queued_jobs')
    op.drop_index(op.f('ix_org_files_worker_id'), table_name='org_files')
    op.drop_index('ix_org_files_status', table_name='org_files')
    op.drop_index('ix_org_files_source', table_name='org_files')
    op.drop_index('ix_org_files_org_id', table_name='org_files')
    op.drop_index('ix_org_files_job_id', table_name='org_files')
    op.drop_index(op.f('ix_org_files_instance_step_id'), table_name='org_files')
    op.drop_index('ix_org_files_instance_id', table_name='org_files')
    op.drop_table('org_files')
    op.drop_index(op.f('ix_iteration_executions_step_id'), table_name='iteration_executions')
    op.drop_index(op.f('ix_iteration_executions_status'), table_name='iteration_executions')
    op.drop_index(op.f('ix_iteration_executions_iteration_group_id'), table_name='iteration_executions')
    op.drop_index('ix_iteration_executions_instance_step_index', table_name='iteration_executions')
    op.drop_index(op.f('ix_iteration_executions_instance_id'), table_name='iteration_executions')
    op.drop_table('iteration_executions')
    op.drop_index(op.f('ix_step_executions_step_key'), table_name='step_executions')
    op.drop_index(op.f('ix_step_executions_status'), table_name='step_executions')
    op.drop_index('ix_step_executions_instance_status', table_name='step_executions')
    op.drop_index(op.f('ix_step_executions_instance_id'), table_name='step_executions')
    op.drop_table('step_executions')
    op.drop_index('ix_workflow_versions_workflow_hash', table_name='workflow_versions')
    op.drop_index('ix_workflow_versions_workflow_created', table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index('ix_instances_workflow_status', table_name='instances')
    op.drop_index('ix_instances_status_created', table_name='instances')
    op.drop_index('ix_instances_organization_status', table_name='instances')
    op.drop_table('instances')
    op.drop_index(op.f('ix_workflows_webhook_token'), table_name='workflows')
    op.drop_index('ix_workflows_slug_pattern', table_name='workflows')
    op.drop_index('ix_workflows_organization_status', table_name='workflows')
    op.drop_index('ix_workflows_organization_scope', table_name='workflows')
    op.drop_index('ix_workflows_has_unresolved_refs', table_name='workflows', postgresql_where=sa.text('has_unresolved_refs = TRUE'))
    op.drop_index('ix_workflows_created_by_scope', table_name='workflows')
    op.drop_index('ix_workflows_blueprint', table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('ix_notifications_recipient_status', table_name='notifications')
    op.drop_index('ix_notifications_organization_status', table_name='notifications')
    op.drop_index('ix_notifications_channel_type', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_notification_channels_user', table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index('ix_blueprints_organization_status', table_name='blueprints')
    op.drop_table('blueprints')
    op.drop_index('ix_audit_events_severity_created', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_severity'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_resource_type'), table_name='audit_events')
    op.drop_index('ix_audit_events_resource', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_org_created', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index('ix_audit_events_category_created', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_actor_created', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_queues_organization_status', table_name='queues')
    op.drop_table('queues')
    op.drop_index('ix_provider_services_service_type_active', table_name='provider_services')
    op.drop_index(op.f('ix_provider_services_service_id'), table_name='provider_services')
    op.drop_table('provider_services')
    op.drop_index('ix_provider_credentials_provider_org', table_name='provider_credentials')
    op.drop_table('provider_credentials')
    op.drop_index('uix_prompt_org_marketplace_slug', table_name='prompts', postgresql_where=sa.text('marketplace_slug IS NOT NULL'))
    op.drop_index(op.f('ix_prompts_organization_id'), table_name='prompts')
    op.drop_index('ix_prompts_org_scope', table_name='prompts')
    op.drop_index('ix_prompts_org_enabled', table_name='prompts')
    op.drop_index('ix_prompts_org_category', table_name='prompts')
    op.drop_index('ix_prompts_marketplace_slug_pattern', table_name='prompts', postgresql_where=sa.text('marketplace_slug IS NOT NULL'))
    op.drop_index('ix_prompts_created_by', table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_organization_secrets_organization_id'), table_name='organization_secrets')
    op.drop_index('ix_org_secrets_org_active', table_name='organization_secrets')
    op.drop_table('organization_secrets')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_site_content_page_id'), table_name='site_content')
    op.drop_table('site_content')
    op.drop_index('ix_providers_slug_pattern', table_name='providers')
    op.drop_index(op.f('ix_providers_slug'), table_name='providers')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_table('providers')
    op.drop_index('ix_package_versions_slug_pattern', table_name='package_versions')
    op.drop_index(op.f('ix_package_versions_slug'), table_name='package_versions')
    op.drop_index('ix_package_versions_active', table_name='package_versions')
    op.drop_table('package_versions')
    op.drop_index(op.f('ix_organizations_status'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_oauth_states_expires_at', table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index('ix_marketplace_catalogs_type_active', table_name='marketplace_catalogs')
    op.drop_index('ix_marketplace_catalogs_fetched', table_name='marketplace_catalogs')
    op.drop_table('marketplace_catalogs')
    op.drop_index('ix_comfyui_workflows_slug_pattern', table_name='comfyui_workflows')
    op.drop_index('ix_comfyui_workflows_slug_active', table_name='comfyui_workflows')
    op.drop_index(op.f('ix_comfyui_workflows_slug'), table_name='comfyui_workflows')
    op.drop_table('comfyui_workflows')
    # ### end Alembic commands ###
