# api/alembic/versions/b44e6ed9519e_worker_enrollment_requests.py

"""worker enrollment requests

Revision ID: b44e6ed9519e
Revises: f220b5c273a0
Create Date: 2026-09-16 10:15:18.347485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b44e6ed9519e'
down_revision: Union[str, Sequence[str], None] = 'f220b5c273a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_enrollment_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('poll_token_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('queues', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['worker_enrollments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_enrollment_requests_poll_token_hash'), 'worker_enrollment_requests', ['poll_token_hash'], unique=True)
    op.create_index('ix_worker_enrollment_requests_status', 'worker_enrollment_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError('Downgrades are not supported. Redeploy the previous major image.')
