# api/alembic/versions/f220b5c273a0_worker_enrollment_link.py

"""worker enrollment link

Revision ID: f220b5c273a0
Revises: 062dc0040854
Create Date: 2026-09-16 09:28:19.147143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f220b5c273a0'
down_revision: Union[str, Sequence[str], None] = '062dc0040854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('enrollment_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_workers_enrollment_id'), 'workers', ['enrollment_id'], unique=False)
    op.create_foreign_key('fk_workers_enrollment_id', 'workers', 'worker_enrollments', ['enrollment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError('Downgrades are not supported. Redeploy the previous major image.')
