// ui/shared/api/index.ts

export { apiRequest, apiFetchBlob, publicApiRequest, getToken } from './core';

export { getServerApiUrl, serverApiFetch } from './server';

export {
  login,
  register,
  logout,
  refreshAccessToken,
  decodeToken,
  getCurrentUser,
  cacheUser,
  storeAuth,
  clearAuth,
  getAuthHeaders,
  getRefreshToken,
  isAuthenticated,
  getOAuthProviders,
  getOAuthAuthorizeUrl,
  isOAuthSupported,
  startOAuthFlow,
  refreshOAuthTokens,
  type LoginResponse,
  type RegisterResponse,
  type RefreshResponse,
  type OAuthProviderInfo,
  type OAuthProvidersResponse,
  type OAuthAuthorizeResponse,
  type OAuthTokenResponse,
} from './auth';

export {
  getCurrentUserProfile,
  profileToUser,
  updateCurrentUserProfile,
  uploadUserAvatar,
  deleteUserAvatar,
  changePassword,
  updateUserAsAdmin,
  createAndInviteUser,
  addOrganizationMember,
  removeOrganizationMember,
  type UserProfile,
  type ChangePasswordResponse,
} from './users';

export {
  getOrganizations,
  getOrganizationStats,
  getOrganization,
  getOrganizationMembers,
  createOrganization,
  updateOrganization,
  getNotification,
  getNotifications,
  markNotificationAsRead,
  markAllNotificationsAsRead,
  type OrganizationStorageStats,
  type OrganizationStats,
  type Organization,
  type OrganizationStatsListResponse,
  type GetOrganizationStatsParams,
  type Notification,
} from './organizations';

export {
  getWorkflows,
  getWorkflowsByBlueprint,
  createWorkflow,
  getWorkflow,
  updateWorkflow,
  deleteWorkflow,
  generateWorkflowWebhookToken,
  regenerateWorkflowWebhookToken,
  deleteWorkflowWebhookToken,
  setWorkflowSchedule,
  clearWorkflowSchedule,
  generateWorkflowApiKey,
  regenerateWorkflowApiKey,
  clearWorkflowApiKey,
  recallWorkflowApiKey,
  listWorkflowTriggerSecretOptions,
  setWorkflowTriggerSecret,
  regenerateTriggerSecretKey,
  setWorkflowEventTrigger,
  clearWorkflowEventTrigger,
  generateStepWebhookToken,
  regenerateStepWebhookToken,
  getStepWebhookToken,
  checkWorkflowCredentials,
  getWorkflowFormSchema,
  submitFormAndStart,
  exportWorkflow,
  importWorkflow,
  getPersonalWorkflows,
  getOrganizationWorkflows,
  copyWorkflow,
  setWorkflowVisibility,
  requestPublish,
  approvePublish,
  rejectPublish,
  getPendingPublish,
  getWorkflowsCatalog,
  getWorkflowDetail,
  getInstalledWorkflows,
  installWorkflowFromMarketplace,
  uninstallMarketplaceWorkflow,
  refreshWorkflowsCatalog,
  type CredentialIssue,
  type CredentialCheckResponse,
  type FormFieldConfigResponse,
  type FormFieldResponse,
  type WorkflowFormSchemaResponse,
  type MarketplaceWorkflow,
  type MarketplaceWorkflowDetail,
  type WorkflowStepPreview,
  type WorkflowConnectionPreview,
  type WorkflowIOField,
  type WorkflowsCatalog,
  type InstalledWorkflowInfo,
  type InstalledWorkflowsResponse,
  type WorkflowInstallResponse,
  type WorkflowScheduleBody,
  type WorkflowScheduleResponse,
  type WorkflowApiKeyResponse,
  type WorkflowEventBody,
} from './workflows';

export {
  getInstances,
  getInstancesByWorkflow,
  getInstanceStatistics,
  createInstance,
  getInstance,
  deleteInstance,
  startInstance,
  pauseInstance,
  resumeInstance,
  runStoppedStep,
  cancelInstance,
  completeInstance,
  failInstance,
  approveInstance,
  triggerStep,
  getJobsForInstance,
  getJob,
  createJob,
  startJob,
  completeJob,
  failJob,
  cancelJob,
  retryJob,
  rerunJobOnly,
  rerunAndContinue,
  rerunStepOnly,
  checkWebhookStatus,
  updateJobResult,
  regenerateResources,
  regenerateIteration,
  type CheckWebhookStatusResponse,
  type PaginatedInstanceResponse,
  type InstanceStatistics,
} from './instances';

export {
  getProviders,
  getProvidersSlim,
  createProvider,
  getProvider,
  updateProvider,
  getProviderPackageDefaults,
  deleteProvider,
  createProviderCredential,
  getProviderCredentials,
  getOrganizationCredentials,
  getProviderCredential,
  revealProviderCredential,
  isCredentialTypeRevealable,
  updateProviderCredential,
  deleteProviderCredential,
  getAllOrganizationCredentials,
  getOrganizationSecrets,
  getOrganizationSecret,
  createOrganizationSecret,
  updateOrganizationSecret,
  deleteOrganizationSecret,
  getOrganizationSecretUsage,
  createProviderService,
  getProviderServices,
  getProviderService,
  updateProviderService,
  deleteProviderService,
  getServicePackageDefaults,
  getAllServices,
  createProviderResource,
  getProviderResources,
  getProviderResourcesByOrganization,
  getProviderResource,
  updateProviderResource,
  deleteProviderResource,
  testProviderService,
  type Provider,
  type ProviderCredential,
  type OrganizationSecret,
  type OrganizationSecretUsage,
  type ProviderServiceResponse,
  type ProviderResource,
  type RevealCredentialResponse,
  type RevealCredentialError,
} from './providers';

export { providerService } from './providerService';

export {
  getSystemHealth,
  getStorageHealth,
  getWorkersHealth,
  deregisterWorker,
  deleteWorker,
  getDatabaseStats,
  getOrganizationStorage,
  getMarketplaceCatalog,
  getMarketplacePackage,
  getEntitlementTokenStatus,
  refreshProvidersCatalog,
  type CatalogRefreshResponse,
  uploadPackage,
  installPackageFromUrl,
  installPackageFromCatalog,
  reinstallPackage,
  checkPackageUsage,
  uninstallPackage,
  getAuditEvents,
  getSystemAuditEvents,
  getResourceAuditHistory,
  getActorAuditHistory,
  type JobStats,
  type StorageStats,
  type WorkerStats,
  type PlatformStats,
  type SystemHealthResponse,
  type DatabaseStats,
  type OrganizationStorageItem,
  type PaginatedStorageResponse,
  type StorageSortField,
  type SortOrder,
  type PackageInstallResponse,
  type InstallFromUrlRequest,
  type PackageUsageInfo,
  type UninstallResponse,
  type AuditEvent,
  type AuditEventListResponse,
  type AuditEventFilters,
} from './admin';

export {
  getDashboardStats,
  getFiles,
  getInstanceFiles,
  getJobFiles,
  downloadFile,
  deleteFile,
  selectFile,
  replaceFile,
  uploadFile,
  uploadFiles,
  uploadFilesToStep,
  addFilesFromLibraryToStep,
  reorderJobFiles,
  reorderStepFiles,
  getResources,
  getInstanceResources,
  getJobResources,
  downloadResource,
  deleteResource,
  selectResource,
  type DashboardStats,
  type FileResource,
} from './files';

export {
  getPersonalPrompts,
  getPendingPublishPrompts,
  requestPublishPrompt,
  approvePublishPrompt,
  rejectPublishPrompt,
  getPrompts,
  getPrompt,
  createPrompt,
  updatePrompt,
  setPromptVisibility,
  deletePrompt,
  copyPrompt,
  importPrompt,
  assemblePrompt,
  getPromptsCatalog,
  getPromptDetail,
  getInstalledPrompts,
  installPrompt,
  uninstallPrompt,
  uploadPromptsCatalog,
  refreshPromptsCatalog,
  type MarketplacePrompt,
  type PromptsCatalogResponse,
  type PromptInstallResponse,
  type InstalledPromptInfo,
  type InstalledPromptsResponse,
  type PromptCatalogUploadResponse,
} from './prompts';

export {
  getPublicSiteContent,
  getPublicBranding,
  getPublicRegistrationSettings,
  getPublicPageVisibility,
  getPublicMaintenanceStatus,
  getPublicContact,
  submitPublicContact,
  getPublicTeam,
  getPublicComplianceSettings,
  getPublicDocsCatalog,
  getPublicPricingPlans,
  type PublicSiteContent,
  type PublicBranding,
  type PublicRegistrationSettings,
  type PublicPageVisibility,
  type PublicMaintenanceStatus,
  type PublicContactInfo,
  type PublicTeamMember,
  type PublicComplianceSettings,
  type DocsManifest,
  getProviderDocsList,
  getProviderDocContent,
  getWorkflowDocContent,
  type ProviderDocInfo,
  type ProviderDocsList,
} from './public';
