# api/app/presentation/api/org_files.py

"""API endpoints for job output resources - files generated by workflow jobs or uploaded by users."""

from typing import List, Optional
from uuid import UUID

from app.config.settings import settings
from fastapi import (
    APIRouter,
    Body,
    Depends,
    File,
    HTTPException,
    Path as PathParam,
    Query,
    Request,
    UploadFile,
    status,
)
from fastapi.responses import FileResponse
from pydantic import BaseModel

from app.application.dtos.org_file_dto import OrgFileResponse
from app.application.interfaces import EntityNotFoundError
from app.application.services.audit_service import AuditService
from app.application.services.org_file import (
    OrgFileService,
)
from app.domain.audit.models import (
    AuditAction,
    AuditActorType,
    AuditCategory,
    AuditSeverity,
    AuditStatus,
    ResourceType,
)
from app.domain.org_file.models import ResourceSource, ResourceStatus
from app.presentation.api.dependencies import (
    CurrentUser,
    get_audit_service,
    get_current_user,
    require_admin,
)

# Empty API_BASE_URL produces relative URLs - works behind a reverse proxy
_API_BASE_URL = settings.API_BASE_URL

router = APIRouter()


from app.presentation.api.dependencies import get_org_file_service
from app.infrastructure.errors import safe_error_message


class ReorderResourcesRequest(BaseModel):
    """Request body for reordering resources within a job."""

    resource_ids: List[UUID]


@router.get("/files", response_model=List[OrgFileResponse])
async def list_organization_files(
    skip: int = Query(0, ge=0, description="Number of records to skip"),
    limit: int = Query(
        settings.API_PAGE_LIMIT_RESOURCE,
        ge=1,
        le=settings.API_PAGE_MAX,
        description="Max number of records",
    ),
    user: CurrentUser = Depends(get_current_user),
    service: OrgFileService = Depends(get_org_file_service),
):
    """
    List all resources for the user's organization with pagination.

    Returns paginated list of job output resources.
    """
    raw_org_id = user.get("org_id")
    if not raw_org_id:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="User has no associated organization",
        )
    organization_id = UUID(raw_org_id)
    resources = await service.get_resources_for_organization(
        organization_id, skip=skip, limit=limit
    )

    api_base_url = _API_BASE_URL

    return [
        OrgFileResponse.from_domain(resource, api_base_url)
        for resource in resources
    ]


@router.get(
    "/instances/{instance_id}/files", response_model=List[OrgFileResponse]
)
async def list_instance_files(
    instance_id: UUID = PathParam(...),
    status: Optional[ResourceStatus] = Query(None, description="Filter by status"),
    source: Optional[ResourceSource] = Query(None, description="Filter by source"),
    user: CurrentUser = Depends(get_current_user),
    service: OrgFileService = Depends(get_org_file_service),
):
    """
    List all resources for a workflow instance.

    Users can only access resources for instances they have access to.
    """
    try:
        resources = await service.get_resources_for_instance(
            instance_id, status=status, source=source
        )

        # Get API base URL from environment
        api_base_url = _API_BASE_URL

        return [
            OrgFileResponse.from_domain(resource, api_base_url)
            for resource in resources
        ]
    except EntityNotFoundError as e:
        raise HTTPException(
            status_code=404,
            detail=safe_error_message(e),
        )


@router.get("/jobs/{job_id}/files", response_model=List[OrgFileResponse])
async def list_job_files(
    job_id: UUID = PathParam(...),
    user: CurrentUser = Depends(get_current_user),
    service: OrgFileService = Depends(get_org_file_service),
):
    """
    List all resources for a specific job execution.

    Users can only access resources for jobs they have access to.
    """
    try:
        resources = await service.get_resources_for_job(job_id)

        api_base_url = _API_BASE_URL

        return [
            OrgFileResponse.from_domain(resource, api_base_url)
            for resource in resources
        ]
    except EntityNotFoundError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=safe_error_message(e),
        )


@router.patch(
    "/jobs/{job_id}/files/reorder", response_model=List[OrgFileResponse]
)
async def reorder_job_files(
    job_id: UUID = PathParam(..., description="Job execution ID"),
    request: ReorderResourcesRequest = Body(...),
    user: CurrentUser = Depends(get_current_user),
    service: OrgFileService = Depends(get_org_file_service),
):
    """
    Reorder files within a job execution.

    Accepts an ordered list of resource IDs. The display_order field
    will be updated to match the order of IDs in the request.

    All resource_ids must belong to the specified job.
    """
    try:
        resources = await service.reorder_resources(job_id, request.resource_ids)

        api_base_url = _API_BASE_URL

        return [
            OrgFileResponse.from_domain(resource, api_base_url)
            for resource in resources
        ]
    except EntityNotFoundError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=safe_error_message(e),
        )


@router.patch(
    "/steps/{step_id}/files/reorder", response_model=List[OrgFileResponse]
)
async def reorder_step_files(
    step_id: UUID = PathParam(..., description="Instance step ID"),
    request: ReorderResourcesRequest = Body(...),
    user: CurrentUser = Depends(get_current_user),
    service: OrgFileService = Depends(get_org_file_service),
):
    """
    Reorder files within an instance step (across all iteration jobs).

    Use this endpoint for iteration workflows where resources from multiple
    jobs need to be reordered together (e.g., user keeps 1 image from each
    of 3 iterations and wants to reorder those 3 images for the next step).

    Accepts an ordered list of resource IDs. The display_order field
    will be updated to match the order of IDs in the request.

    All resource_ids must belong to the specified step.
    """
    try:
        resources = await service.reorder_step_resources(step_id, request.resource_ids)

        api_base_url = _API_BASE_URL

        return [
            OrgFileResponse.from_domain(resource, api_base_url)
            for resource in resources
        ]
    except EntityNotFoundError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=safe_error_message(e),
        )


@router.get("/files/{file_id}", response_model=OrgFileResponse)
async def get_file(
    file_id: UUID = PathParam(...),
    user: CurrentUser = Depends(get_current_user),
    service: OrgFileService = Depends(get_org_file_service),
):
    """Get file metadata by ID."""
    resource = await service.get_resource(file_id)

    if not resource:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"File {file_id} not found",
        )

    api_base_url = _API_BASE_URL
    return OrgFileResponse.from_domain(resource, api_base_url)


@router.get("/files/{file_id}/download")
async def download_file(
    request: Request,
    file_id: UUID = PathParam(...),
    user: CurrentUser = Depends(get_current_user),
    service: OrgFileService = Depends(get_org_file_service),
    audit_service: AuditService = Depends(get_audit_service),
):
    """
    Download a file.

    Returns the actual file for download.
    """
    ip_address = request.client.host if request.client else None
    user_id = user.get("id") or user.get("sub") or ""
    org_id = user.get("org_id")

    async def _audit(
        *, status_val: AuditStatus = AuditStatus.SUCCESS, error_msg=None, filename=None
    ):
        try:
            await audit_service.log_event(
                actor_id=UUID(str(user_id)) if user_id else None,
                actor_type=AuditActorType(user.get("role") or "user"),
                action=AuditAction.DOWNLOAD,
                resource_type=ResourceType.FILE,
                resource_id=file_id,
                resource_name=filename,
                organization_id=UUID(org_id) if org_id else None,
                severity=(
                    AuditSeverity.WARNING
                    if status_val == AuditStatus.FAILED
                    else AuditSeverity.INFO
                ),
                category=AuditCategory.ACCESS,
                status=status_val,
                error_message=error_msg,
                metadata={"ip_address": ip_address},
            )
        except Exception:
            pass

    try:
        file_path, mime_type = await service.get_resource_file_path(file_id)

        if not file_path.exists():
            await _audit(
                status_val=AuditStatus.FAILED, error_msg="File not found on disk"
            )
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="File not found on disk",
            )

        await _audit(filename=file_path.name)

        return FileResponse(
            path=str(file_path),
            media_type=mime_type,
            filename=file_path.name,
        )
    except EntityNotFoundError as e:
        await _audit(status_val=AuditStatus.FAILED, error_msg=str(e))
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=safe_error_message(e),
        )


@router.get("/files/{file_id}/preview")
async def preview_file(
    file_id: UUID = PathParam(...),
    user: CurrentUser = Depends(get_current_user),
    service: OrgFileService = Depends(get_org_file_service),
):
    """
    Get thumbnail/preview of a file.

    Returns the thumbnail image if available.
    """
    thumbnail_path = await service.get_resource_thumbnail_path(file_id)

    if not thumbnail_path or not thumbnail_path.exists():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Thumbnail not available for this file",
        )

    return FileResponse(
        path=str(thumbnail_path),
        media_type="image/jpeg",
        filename=f"{file_id}_thumbnail.jpg",
    )


@router.delete("/files/{file_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_file(
    request: Request,
    file_id: UUID = PathParam(...),
    user: CurrentUser = Depends(get_current_user),
    admin: bool = Depends(require_admin),
    service: OrgFileService = Depends(get_org_file_service),
    audit_service: AuditService = Depends(get_audit_service),
):
    """
    Delete a file (admin only).

    Soft deletes the database record and removes files from disk.
    """
    ip_address = request.client.host if request.client else None
    user_id = user.get("id") or user.get("sub") or ""
    org_id = user.get("org_id")

    async def _audit(
        *, status_val: AuditStatus = AuditStatus.SUCCESS, error_msg=None, filename=None
    ):
        try:
            await audit_service.log_event(
                actor_id=UUID(str(user_id)) if user_id else None,
                actor_type=AuditActorType(user.get("role") or "user"),
                action=AuditAction.DELETE,
                resource_type=ResourceType.FILE,
                resource_id=file_id,
                resource_name=filename,
                organization_id=UUID(org_id) if org_id else None,
                severity=AuditSeverity.WARNING,
                category=AuditCategory.ACCESS,
                status=status_val,
                error_message=error_msg,
                metadata={"ip_address": ip_address},
            )
        except Exception:
            pass

    # Fetch resource metadata before deletion for audit logging
    resource = await service.get_resource(file_id)
    if not resource:
        await _audit(status_val=AuditStatus.FAILED, error_msg="Resource not found")
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"File {file_id} not found",
        )

    # Store filename for audit logging before deletion
    filename = resource.display_name

    try:
        await service.delete_resource(file_id)
        await _audit(filename=filename)
    except EntityNotFoundError as e:
        await _audit(status_val=AuditStatus.FAILED, error_msg=str(e), filename=filename)
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=safe_error_message(e),
        )


@router.post("/files/upload", response_model=List[OrgFileResponse])
async def upload_files(
    files: List[UploadFile] = File(..., description="Files to upload (max 10)"),
    user: CurrentUser = Depends(get_current_user),
    service: OrgFileService = Depends(get_org_file_service),
):
    """
    Upload files to the organization's file library.

    Creates standalone file resources not tied to any workflow instance.
    These files can be used as inputs in workflows or stored for later use.
    Supports up to 10 files per request with automatic thumbnail generation for images.
    """
    import logging
    import mimetypes

    logger = logging.getLogger(__name__)

    # Validate files were provided
    if not files:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No files provided",
        )

    # Limit number of files per upload
    if len(files) > 10:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Maximum 10 files per upload",
        )

    # Get organization ID from user
    org_id = user.get("org_id")
    if not org_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Organization ID not found in user token",
        )

    created_resources = []
    for file in files:
        if not file or not file.filename:
            continue

        # Get file extension from filename
        file_extension = ""
        ext_index = file.filename.rfind(".")
        if ext_index != -1:
            file_extension = file.filename[ext_index:]

        # Determine MIME type
        mime_type = file.content_type
        if not mime_type or mime_type == "application/octet-stream":
            guessed_type, _ = mimetypes.guess_type(file.filename or "")
            mime_type = guessed_type or "application/octet-stream"

        # Read file content
        content = await file.read()
        file_size = len(content)

        # Create BytesIO wrapper for the service
        from io import BytesIO

        file_stream = BytesIO(content)

        try:
            resource = await service.upload_file(
                organization_id=UUID(org_id),
                file_content=file_stream,
                file_size=file_size,
                mime_type=mime_type,
                file_extension=file_extension,
                display_name=file.filename or "uploaded_file",
            )
            created_resources.append(resource)

            logger.info(
                f"File uploaded: name={file.filename}, size={file_size}, "
                f"org={org_id}, user={user.get('sub')}"
            )
        except Exception as e:
            logger.error(f"File upload failed for {file.filename}: {e}")
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Failed to upload file {file.filename}",
            )

    if not created_resources:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No files were successfully uploaded",
        )

    api_base_url = _API_BASE_URL
    return [
        OrgFileResponse.from_domain(resource, api_base_url)
        for resource in created_resources
    ]


@router.post("/files/{file_id}/replace", response_model=OrgFileResponse)
async def replace_file(
    file_id: UUID = PathParam(..., description="Resource ID to replace"),
    file: UploadFile = File(...),
    user: CurrentUser = Depends(get_current_user),
    service: OrgFileService = Depends(get_org_file_service),
):
    """
    Replace a file's content with a user-uploaded file.

    This allows users to replace generated files with their own local files
    while preserving the resource's position in the workflow.

    The original file will be deleted and replaced with the uploaded file.
    """
    import logging
    import mimetypes

    logger = logging.getLogger(__name__)

    # Validate file was provided
    if not file or not file.filename:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="No file provided",
        )

    # Get file extension from filename
    file_extension = ""
    ext_index = file.filename.rfind(".")
    if ext_index != -1:
        file_extension = file.filename[ext_index:]

    # Determine MIME type
    mime_type = file.content_type
    if not mime_type or mime_type == "application/octet-stream":
        # Try to guess from extension
        guessed_type, _ = mimetypes.guess_type(file.filename or "")
        mime_type = guessed_type or "application/octet-stream"

    # Read file to get size (we need to pass BinaryIO to service)
    # Reset file position after reading
    content = await file.read()
    file_size = len(content)

    # Create a BytesIO wrapper for the service
    from io import BytesIO

    file_stream = BytesIO(content)

    try:
        resource = await service.replace_resource(
            resource_id=file_id,
            file_content=file_stream,
            file_size=file_size,
            mime_type=mime_type,
            file_extension=file_extension,
            display_name=file.filename,
        )

        logger.info(
            f"File replaced: file_id={file_id}, new_name={file.filename}, "
            f"size={file_size}, user={user.get('sub')}"
        )

        api_base_url = _API_BASE_URL
        return OrgFileResponse.from_domain(resource, api_base_url)

    except EntityNotFoundError as e:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=safe_error_message(e),
        )
